# Config Documentation: https://github.com/LonghiTW/TileMapper/wiki

enabled: true
active_blockset: "Default"
active_source: osm

tile_sources:
  osm:
    url: "https://{random:a,b,c}.tile.openstreetmap.org/{z}/{x}/{y}.png"
    zoom: 18
    offset:
      x: 0
      z: 0
  bing:
    url: "https://t.ssl.ak.dynamic.tiles.virtualearth.net/comp/ch/{u}?it=A&shading=hill"
    zoom: 20
    offset:
      x: 0
      z: 0
  yandex:
    url: "https://core-sat.maps.yandex.net/tiles?l=sat&x={x}&y={y}&z={z}"
    zoom: 20
    offset:
      x: 0
      z: 0
  tw:
    url: "https://wmts.nlsc.gov.tw/wmts/PHOTO2/default/GoogleMapsCompatible/{z}/{y}/{x}.png"
    zoom: 20
    offset:
      x: -0.625
      z: 0.3125

max_concurrent_requests: 2
cache_size: 1000
surface_block_mask: false
config_version: "1.0"
